// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBYn1vOk5W1W5o9yICzuKI2I6-qkO1AVo',
    appId: '1:646019631586:web:1a0bb850e56ad32b5c91bb',
    messagingSenderId: '646019631586',
    projectId: 'weather-test-gaz',
    authDomain: 'weather-test-gaz.firebaseapp.com',
    storageBucket: 'weather-test-gaz.appspot.com',
    measurementId: 'G-FD96QCT2D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfFSnCuwAlZ5Qq6VdS5yKDUFHTQP-Pwqk',
    appId: '1:646019631586:android:7a38cb7eceda24515c91bb',
    messagingSenderId: '646019631586',
    projectId: 'weather-test-gaz',
    storageBucket: 'weather-test-gaz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg6R3krE8SkockrHBKA2oWVCBGuqRdecs',
    appId: '1:646019631586:ios:dfec26c2622b87b15c91bb',
    messagingSenderId: '646019631586',
    projectId: 'weather-test-gaz',
    storageBucket: 'weather-test-gaz.appspot.com',
    iosClientId: '646019631586-8s4ggphunmfctbqknk033oe6dvgsmk9f.apps.googleusercontent.com',
    iosBundleId: 'ru.andlancer.testweather.testweathergaz',
  );
}
